# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1d30f819159f3b190e22bef7ea16fe0272c6583dcfd0f3f37addf21eb56c0a6acb135fe08d295a506c63d02dff53b5bad60c2d78740fff304c33b52abce7ffe
  salt: "1438594635"
  secret_key: '1234qwer'
  iv: "\xAA\xB1\xB2xi\e|stJj>\xF1tu#"

test:
  secret_key_base: f4b50a33177b13181fb69be51f2a86f54296f59c9c4e861f43e9d40d37cb2dc302940ce3122495a2bfe1c55c488bada7b461c58ebe0795120196207f051c91a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 21bbfb5ec0f24f6da70e48c66e6cf830e30a5dd4bc020d8661787e4d7730fccf970bd22f90aa2bac866000c2447a82eb5a8c8f533478c8c5a714be4fc9c9d593
  salt: "1440759306"
  secret_key: '1234qwer'
  iv: "5J\xA5`\xAFX\x0E|\xFF\\\xBE\x98\x11\x87\x82M"
